import discord
import random
import requests
import datetime
from discord import app_commands
import string

# Discord bot setup
intents = discord.Intents.default()
# Slash command imports
client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)  # for slash commands
# Config
deny_perms = "❗ You do not have permission to use this command."

#################################### CHANGE THESE ####################################

# Tebex API setup (https://docs.tebex.io/plugin/authentication)
tebex_secret = "CHANGE ME"
# Discord bot token
bot_token = "CHANGE ME"
guild_id = 937002686996443217  # RIGHT-CLICK YOUR SERVER AND CLICK COPY ID (Need to have Developer mode on)
allowed_user_ids = [83160441982816256, 82991096577134592, 333058262431694848]  # List of allowed user IDs
currency = "$"
store_link = "https://store.vanillymc.net/"
image_link = "https://i.imgur.com/RoWDsci.png"
hex_color = "#A180D0"
######################################################################################

# Event triggered when the bot is ready and connected to Discord
@client.event
async def on_ready():
    print(f"Tebex Coupon bot is connected as {client.user.name}.")
    await tree.sync(guild=discord.Object(id=guild_id))


def generate_coupon_code():
    characters = string.ascii_uppercase + string.digits
    coupon_code = ''.join(random.choice(characters) for _ in range(4))
    coupon_code += '-' + ''.join(random.choice(characters) for _ in range(4))
    coupon_code += '-' + ''.join(random.choice(characters) for _ in range(4))
    return coupon_code


#################################### SLASH COMMAND ####################################
@tree.command(
    name="generatecoupon",
    description="💵 Used to generate Tebex coupons.",
    guild=discord.Object(id=guild_id)  # Add the guild ids in which the slash command will appear.
)
async def coupon_command(interaction: discord.Interaction, value: int, note: str):
    currentDate = f"{datetime.datetime.now():%Y-%m-%d}"
    midnightUTC = "T00:00:00+0000"

    if interaction.user.id in allowed_user_ids:
        coupon_code = generate_coupon_code()
        url = 'https://plugin.tebex.io/coupons'
        headers = {'X-Tebex-Secret': tebex_secret}
        payload = {
            'code': coupon_code,  # Use the generated coupon code
            'effective_on': 'cart',
            'discount_type': 'value',
            'discount_amount': value,  # Replace with the desired discount amount
            'discount_percentage': 0,
            'redeem_unlimited': False,
            'expire_never': True,
            'expire_limit': 1,
            'expire_date': '2030-01-01',
            'discount_application_method': 2,
            'basket_type': 'single',
            'start_date': f"{currentDate}{midnightUTC}",
            'note': note,
        }
        response = requests.post(url, headers=headers, json=payload)
        print(response.status_code)

        if response.status_code == 200:
            coupon = response.json().get('coupon', {}).get('code')
            if coupon:
                print("Code could not generate.")
            else:
                offender = interaction.user.id
                embed = await generate_coupon(coupon_code, value, offender)
                await interaction.response.send_message(embed=embed)
        else:
            error_message = response.json().get('error_message', 'Unknown error')
            await interaction.response.send_message(f"Coupon generation failed. Error: {error_message}", ephemeral=True)
    else:
        await interaction.response.send_message(deny_perms, ephemeral=True)


# Send banning embed
async def generate_coupon(code, value, generated_by):
    # Convert hex color to RGB
    rgb_color = tuple(int(hex_color[i:i + 2], 16) for i in (1, 3, 5))  # Skip the '#' at the start
    embed = discord.Embed(
        title=f"Coupon has been generated 💵",
        description=f"",
        color=discord.Color.from_rgb(*rgb_color)
    )

    embed.add_field(name="Coupon Code: ", value=f"{code}", inline=False)
    embed.add_field(name="Value", value=f"{currency}{value}", inline=False)
    embed.add_field(name="Generated by:", value=f"<@{generated_by}>", inline=False)
    embed.add_field(name="Where to use:", value=store_link, inline=False)
    embed.set_image(url=image_link)

    return embed


# Run the Discord bot
client.run(bot_token)
